Removed remaining mock API code.

diff --git a/deploy/hooks/common b/deploy/hooks/common
--- a/deploy/hooks/common
+++ b/deploy/hooks/common
@@ -23,7 +23,7 @@ rollback_abort() {
 	if [ ${ROLLBACK} -eq 1 ]; then
 		local path=${DEPLOY_ROOT}/${DEPLOY_ENV}/$1
 		echo Removing ${path}
-		rm -r ${path}
+		rm -rf ${path}
 	fi
 	exit 1
 }
@@ -54,7 +54,7 @@ repo_clone() {
 		abort "$1 is already deployed, aborting".
 	fi
 	git clone ${PWD} ${dest}
-    test $? -eq 0 || abort "Failed to clone ${PWD} into ${dest}"
+	test $? -eq 0 || abort "Failed to clone ${PWD} into ${dest}"
 }
 
 repo_checkout_tag() {
@@ -63,7 +63,7 @@ repo_checkout_tag() {
 	# git looks at $GIT_DIR first before checking $PWD, so let's fix that.
 	unset GIT_DIR
 	git checkout $1
-    test $? -eq 0 || rollback_abort $1 "Failed to checkout $1, aborting."
+	test $? -eq 0 || rollback_abort $1 "Failed to checkout $1, aborting."
 }
 
 repo_checkout_branch() {
@@ -89,8 +89,8 @@ npm_install() {
 grunt_build() {
 	cd ${DEPLOY_ROOT}/${DEPLOY_ENV}/$1
 	echo "Running build with Grunt..."
-	APP_SETTINGS=${DEPLOY_ROOT}/${DEPLOY_ENV}/settings.js APP_NAME=${DEPLOY_ENV} NODE_ENV=production APP_CACHEDIR=${DEPLOY_ROOT}/${DEPLOY_ENV}/shared/cache grunt build
-	test $? -eq 0 || rollback_abort $1 "Grunt build failed. Fix and redeploy."
+	APP_SETTINGS=${DEPLOY_ROOT}/${DEPLOY_ENV}/settings.js APP_NAME=${DEPLOY_ENV} NODE_ENV=production grunt build
+	test $? -eq 0 || abort $1 "Grunt build failed. Fix and redeploy."
 }
 
 repo_link() {
